# Generated by Django 5.2.6 on 2025-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "short",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=2048)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
